workspace:
  base: /go/src

clone:
  git:
    image: plugins/git
    tags: true

pipeline:
  build:
    image: quay.io/honestbee/monorepo
    pull: true
    commands:
      - mbt build diff --from `git rev-list --tags --max-count=2 | tail -n 1` --to ${DRONE_COMMIT_SHA}
    when:
      event: tag

  github_release:
    image: plugins/github-release
    repo_owner: honestbee
    repo_name: devops-tools
    secrets: [ github_token ]
    files: bin/*
    when:
      event: tag
